settings:
  application:
    host: 127.0.0.1
    port: 8888
    apiVersion: /api/v1
    timeOut: 60
    secret: AqzeA#w*FQte_kqYPtFNZOR&fFVuYIPe
    secretExpire: 86400
    PageSize: 10
    PageMaxSize: 1000
  mysql:
    dbType: mysql
    host: 127.0.0.1
    dbName: rudder
    password: admin
    port: 3306
    username: root
    charSet: utf8mb4
  gorm:
    maxIdleConn: 3
    maxOpenConn: 2000
    logLevel: info         # info|warn|error|silent